[env]
COVERAGE_TARGET_DIRECTORY="${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/cover"
COVERAGE_BINARIES="${COVERAGE_TARGET_DIRECTORY}/debug/deps"
COVERAGE_PROF_OUTPUT="${COVERAGE_BINARIES}/profraw"
COVERAGE_OUTPUT_LCOV="${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/lcov.info"

[tasks.coverage_grcov_build]
private=true
toolchain = "nightly"
command = "cargo"
args = ["build"]

  [tasks.coverage_grcov_build.env]
  "CARGO_BUILD_TARGET_DIR"="${COVERAGE_TARGET_DIRECTORY}"
  "RUSTFLAGS"= "-Cinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
  "RUSTDOCFLAGS"="-Cpanic=abort"

[tasks.coverage_grcov_run_test]
private=true
toolchain="nightly"
command = "cargo"
args = ["test", "--verbose"]

  [tasks.coverage_grcov_run_test.env]
  "CARGO_BUILD_TARGET_DIR"="${COVERAGE_TARGET_DIRECTORY}"
  "LLVM_PROFILE_FILE"="${COVERAGE_PROF_OUTPUT}/coverage-%p-%m.profraw"

[tasks.coverage_grcov_prepare_outdir]
private=true
workspace=true
script='''
#!/usr/bin/env bash
set -eux

rm -rf ${COVERAGE_PROF_OUTPUT}
mkdir ${COVERAGE_PROF_OUTPUT}
'''

[tasks.coverage_grcov]
workspace=true
install_crate= {crate_name="grcov"}
env = {"RUSTUP_TOOLCHAIN"="nightly"}
script = '''
#!/usr/bin/env bash
set -eux

grcov ${COVERAGE_PROF_OUTPUT} \
  -b ${COVERAGE_BINARIES} -s ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY} \
  -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/lcov.info
'''
dependencies=["coverage_grcov_build", "coverage_grcov_prepare_outdir", "coverage_grcov_run_test"]
